# Generated by Django 3.1.2 on 2020-10-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201001_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.FloatField(),
        ),
    ]
